name=SST39LF401C
version=1.0.0
author=Jack Pyburn
maintainer=Jack Pyburn <jwp0030@uah.edu>
sentence=A library to interface with the SST39LF401C IC
paragraph=This library provides high-level functions for programming and erasing the SST39LF401C NOR Flash IC
url=
architectures=sam
